-- Thêm cột OrderItemsJson vào bảng Orders
ALTER TABLE Orders ADD COLUMN OrderItemsJson TEXT;

-- Thêm các cột khác nếu chưa có
ALTER TABLE Orders ADD COLUMN OrderNumber VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN CustomerName VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN Phone VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN Email VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN Address TEXT NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN Note TEXT;
ALTER TABLE Orders ADD COLUMN PaymentMethod VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE Orders ADD COLUMN PaymentStatus VARCHAR(20) NOT NULL DEFAULT 'Pending';
ALTER TABLE Orders ADD COLUMN OrderStatus VARCHAR(20) NOT NULL DEFAULT 'Pending';
ALTER TABLE Orders ADD COLUMN CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Orders ADD COLUMN EstimatedDelivery DATETIME;
ALTER TABLE Orders ADD COLUMN CompletedAt DATETIME;
ALTER TABLE Orders ADD COLUMN CouponCode VARCHAR(50);
ALTER TABLE Orders ADD COLUMN DiscountAmount DECIMAL(10,2) DEFAULT 0;

-- Thêm các cột mới cho string status
ALTER TABLE Orders ADD COLUMN PaymentStatusString VARCHAR(20) DEFAULT 'Pending';
ALTER TABLE Orders ADD COLUMN OrderStatusString VARCHAR(20) DEFAULT 'Pending'; 