[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet run"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.variables]
ASPNETCORE_ENVIRONMENT = "Production" 