services:
  - type: web
    name: nui-tea-api
    env: dotnet
    plan: free
    buildCommand: dotnet build
    startCommand: dotnet run
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false 