services:
  - type: web
    name: nui-tea-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false 